version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  AfterInstall:
    - location: scripts/AfterInstallHook.sh
      timeout: 300
  ApplicationStart:
    - location: scripts/AppStart.sh
