version: 0.2
phases:
  install: 
    runtime-versions:
      nodejs: 16.x
      
  pre_build:
    commands:
      - echo Installing dependencies...
      - npm install -g pnpm
      - pnpm install
  build:
    commands:
      - echo Init build step `date`
      - echo Run lint
      - pnpm lint
      - echo Run tests
      - pnpm test
      - echo Building
      - pnpm build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'